In [1]:
import pandas as pd

In [3]:
nav_df = pd.read_csv("C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/nav_history.csv")

In [4]:
nav_df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [6]:
nav_df.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [7]:
nav_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [9]:
nav_df.duplicated().sum()

np.int64(0)

In [11]:
nav_df["date"] = pd.to_datetime(nav_df["date"],errors="coerce")

In [12]:
nav_df["date"].isnull().sum()

np.int64(0)

In [13]:
nav_df["nav"] = pd.to_numeric(nav_df["nav"],errors="coerce")

In [15]:
invalid_nav = nav_df[nav_df["nav"] <= 0]

print(invalid_nav)

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [16]:
nav_df = nav_df[nav_df["nav"] > 0]

In [19]:
nav_df =nav_df.sort_values(by =["amfi_code","date"])

In [20]:
nav_df["nav"]= nav_df.groupby("amfi_code")["nav"].ffill()

In [22]:
import os

nav_df.to_csv("C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/nav_history.csv",index=False)

In [23]:
txn_df= pd.read_csv("C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/investor_transactions.csv")

In [24]:
txn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [25]:
txn_df.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [26]:
txn_df["transaction_type"].unique()

array(['SIP', 'Redemption', 'Lumpsum'], dtype=object)

In [27]:
txn_df["transaction_type"] = (txn_df["transaction_type"].str.strip().str.lower())

In [28]:
mapping = {
    "sip": "SIP",
    "lumpsum": "Lumpsum",
    "redemption": "Redemption",
}

txn_df["transaction_type"] = (
    txn_df["transaction_type"]
    .replace(mapping)
)

In [29]:
txn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [31]:
txn_df.head(10)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
5,INV001497,2024-01-01,101208,SIP,3295,Maharashtra,Mumbai,T30,36-45,Male,56.8,Mandate,Verified
6,INV000786,2024-01-01,101208,SIP,15047,Madhya Pradesh,Bhopal,B30,26-35,Male,17.9,Mandate,Verified
7,INV000616,2024-01-01,100016,SIP,933,Maharashtra,Nashik,B30,36-45,Male,50.4,Mandate,Verified
8,INV003670,2024-01-01,119120,SIP,10672,Punjab,Chandigarh,T30,36-45,Male,38.4,Net Banking,Verified
9,INV002054,2024-01-01,148567,SIP,1111,Telangana,Hyderabad,T30,26-35,Male,17.8,Net Banking,Verified

In [32]:
txn_df["amount_inr"] = pd.to_numeric(txn_df["amount_inr"],errors="coerce")

In [33]:
invalid_amounts = txn_df[txn_df["amount_inr"]<=0]

print(invalid_amounts)

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, transaction_type, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status]
Index: []

In [34]:
txn_df["transaction_date"] = pd.to_datetime(txn_df["transaction_date"],errors="coerce")

In [36]:
txn_df["transaction_date"].isnull().sum()

np.int64(0)

In [37]:
print(txn_df["kyc_status"].unique())

['Verified' 'Pending']

In [38]:
txn_df["kys_status"]=(txn_df["kyc_status"].str.strip().str.title())

In [40]:
valid_kyc = [
    "Verified",
    "Pending"
]

invalid_kyc = txn_df[
    ~txn_df["kyc_status"]
    .isin(valid_kyc)
]

print(invalid_kyc)

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, transaction_type, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status, kys_status]
Index: []

In [41]:
print(txn_df["gender"].unique())

['Female' 'Male']

In [42]:
txn_df["city_tier"].unique()

array(['T30', 'B30'], dtype=object)

In [43]:
txn_df.duplicated().sum()

np.int64(0)

In [44]:
print(txn_df.info())

print(txn_df.isnull().sum())

print(txn_df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
 13  kys_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(10)
memory usage: 3.5+ MB
None
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
kys_status            0
dtype: int64
0

In [50]:
import os
txn_df.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/investor_transactions.csv",
    index=False
)

In [52]:
perf_df=pd.read_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/scheme_performance.csv")

perf_df.head()
perf_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [53]:
perf_df.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [54]:
perf_df.duplicated().sum()

np.int64(0)

In [55]:
perf_df.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')

In [58]:
numeric_cols = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct",
    "benchmark_3yr_pct",
    "alpha",
    "beta",
    "sharpe_ratio",
    "sortino_ratio",
    "std_dev_ann_pct",
    "max_drawdown_pct",
    "aum_crore",
    "expense_ratio_pct",
    "morningstar_rating"
]

for col in numeric_cols:

    perf_df[col] = pd.to_numeric(
        perf_df[col],
        errors="coerce"
    )

In [59]:
return_cols = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct"
]

for col in return_cols:

    anomalies = perf_df[
        (perf_df[col] < -100) |
        (perf_df[col] > 200)
    ]

    print(f"\nAnomalies in {col}")
    print(anomalies[[col]])

Anomalies in return_1yr_pct
Empty DataFrame
Columns: [return_1yr_pct]
Index: []

Anomalies in return_3yr_pct
Empty DataFrame
Columns: [return_3yr_pct]
Index: []

Anomalies in return_5yr_pct
Empty DataFrame
Columns: [return_5yr_pct]
Index: []

In [60]:
invalid_expense = perf_df[
    (perf_df["expense_ratio_pct"] < 0.1) |
    (perf_df["expense_ratio_pct"] > 2.5)
]

print(invalid_expense)

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [61]:
invalid_rating = perf_df[
    ~perf_df["morningstar_rating"].isin(
        [1, 2, 3, 4, 5]
    )
]

print(invalid_rating)

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [62]:
invalid_beta = perf_df[
    (perf_df["beta"] < 0) |
    (perf_df["beta"] > 5)
]

print(invalid_beta)

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [63]:
perf_df["fund_house"] = (
    perf_df["fund_house"]
    .str.strip()
    .str.title()
)

In [66]:
perf_df["category"] = (
    perf_df["category"]
    .str.strip()
    .str.title()
)

In [65]:
perf_df["risk_grade"] = (
    perf_df["risk_grade"]
    .str.strip()
    .str.title()
)

In [67]:
perf_df = perf_df.drop_duplicates(
    subset=["amfi_code"]
)

In [68]:
print(perf_df.info())

print(perf_df.isnull().sum())

print(perf_df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB
None
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64
0

In [69]:
perf_df.to_csv("C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/scheme_performance_cleaned.csv",index=False)

In [98]:
dim_fund = pd.read_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/fund_master_cleaned.csv"
)

print(fund_df.head())

print(fund_df.info())

   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  14-02-2006              NIFTY 100 TRI
1   Equity    Large Cap   Direct  01-01-2013              NIFTY 100 TRI
2   Equity    Small Cap  Regular  09-09-2009       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  01-01-2013       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  30-12-2000  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_grade sebi_category_code
0  Sohini Andani   Moderate               EC01
1  Sohini Andani   Moderate               EC01
2  R. Srinivasan  Very High               EC03
3  R. Srinivasan  Very High               EC03
4   Dinesh Ahuja        Low               DC02
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_grade          40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB
None

In [71]:
fund_df.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [72]:
fund_df = fund_df.drop_duplicates(
    subset=["amfi_code"]
)

In [91]:
fund_df.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_grade', 'sebi_category_code'],
      dtype='object')

In [77]:
fund_df["amfi_code"] = pd.to_numeric(
    fund_df["amfi_code"],
    errors="coerce"
)

In [78]:
print(
    fund_df["amfi_code"]
    .isnull()
    .sum()
)

0

In [79]:
print(
    fund_df["category"]
    .unique()
)

['Equity' 'Debt']

In [80]:
print(
    fund_df["plan"]
    .unique()
)

['Regular' 'Direct']

In [92]:
print(fund_df.info())

print(fund_df.isnull().sum())

print(fund_df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_grade          40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB
None
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_grade            0
sebi_category_code    0
dtype: int64
0

In [95]:
fund_df.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/fund_master_cleaned.csv",
    index=False
)

In [83]:
fund_df.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [85]:
fund_df = fund_df.rename(
    columns={
        "risk_category": "risk_grade"
    }
)

In [86]:
fund_df.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_grade', 'sebi_category_code'],
      dtype='object')

In [99]:


dim_fund["amfi_code"] = (
    pd.to_numeric(
        dim_fund["amfi_code"],
        errors="coerce"
    )
)

dim_fund = dim_fund.dropna(
    subset=["amfi_code"]
)

dim_fund["amfi_code"] = (
    dim_fund["amfi_code"]
    .astype(int)
)

dim_fund = dim_fund.drop_duplicates(
    subset=["amfi_code"]
)

dim_fund = dim_fund.reset_index(drop=True)

print("dim_fund cleaned")
print(dim_fund.shape)
print(dim_fund["amfi_code"].nunique())

dim_fund cleaned
(40, 15)
40

In [102]:
txn_df.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status', 'kys_status'],
      dtype='object')

In [103]:
dim_fund = fund_df[
    [
        "amfi_code",
        "scheme_name",
        "fund_house",
        "category",
        "plan",
        "risk_grade"
    ]
].copy()

In [104]:
dim_date = pd.DataFrame()

dim_date["full_date"] = nav_df["date"]

dim_date = dim_date.drop_duplicates(
    subset=["full_date"]
)

dim_date = dim_date.reset_index(drop=True)

dim_date["day"] = (
    dim_date["full_date"].dt.day
)

dim_date["month"] = (
    dim_date["full_date"].dt.month
)

dim_date["quarter"] = (
    dim_date["full_date"].dt.quarter
)

dim_date["year"] = (
    dim_date["full_date"].dt.year
)

dim_date["weekday_name"] = (
    dim_date["full_date"].dt.day_name()
)

In [105]:
fact_nav = nav_df[
    [
        "amfi_code",
        "date",
        "nav"
    ]
].copy()

fact_nav = fact_nav.rename(
    columns={
        "date": "nav_date"
    }
)

In [108]:
fact_transactions = txn_df[
    [
        "investor_id",
        "amfi_code",
        "transaction_date",
        "transaction_type",
        "amount_inr",
        "state",
        "city",
        "city_tier",
        "age_group",
        "gender",
        "annual_income_lakh",
        "payment_mode",
        "kyc_status"
    ]
].copy()

In [109]:
fact_performance = perf_df[
    [
        "amfi_code",
        "return_1yr_pct",
        "return_3yr_pct",
        "return_5yr_pct",
        "benchmark_3yr_pct",
        "alpha",
        "beta",
        "sharpe_ratio",
        "sortino_ratio",
        "std_dev_ann_pct",
        "max_drawdown_pct",
        "expense_ratio_pct",
        "morningstar_rating"
    ]
].copy()

In [111]:
fact_aum = perf_df[
    [
        "amfi_code",
        "aum_crore"
    ]
].copy()

In [112]:
dim_fund.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/dim_fund.csv",
    index=False
)

dim_date.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/dim_date.csv",
    index=False
)

In [113]:
fact_nav.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/fact_nav.csv",
    index=False
)

fact_transactions.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/fact_transactions.csv",
    index=False
)

fact_performance.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/fact_performance.csv",
    index=False
)

fact_aum.to_csv(
    "C:/Users/abdul/OneDrive/Desktop/Bluestock_capstone/data/processed/fact_aum.csv",
    index=False
)

In [114]:
print(dim_fund.shape)
print(dim_date.shape)
print(fact_nav.shape)
print(fact_transactions.shape)
print(fact_performance.shape)
print(fact_aum.shape)

(40, 6)
(1150, 6)
(46000, 3)
(32778, 13)
(40, 13)
(40, 2)